# Generated by Django 6.0.5 on 2026-05-30 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('influencers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('industry', models.CharField(choices=[('fashion', 'Fashion'), ('beauty', 'Beauty & Cosmetics'), ('tech', 'Technology'), ('food', 'Food & Beverage'), ('health', 'Health & Wellness'), ('finance', 'Finance'), ('travel', 'Travel & Hospitality'), ('education', 'Education'), ('retail', 'Retail & E-commerce'), ('entertainment', 'Entertainment'), ('sports', 'Sports & Fitness'), ('other', 'Other')], default='other', max_length=50)),
                ('website', models.URLField(blank=True)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('500+', '500+')], max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='brand_covers/')),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_campaigns', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='influencers.influencerprofile')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='brands.brandprofile')),
            ],
            options={
                'unique_together': {('brand', 'influencer')},
            },
        ),
    ]
