# Generated by Django 6.0.5 on 2026-06-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerprofile',
            name='languages',
            field=models.CharField(blank=True, default='Hindi, English', max_length=200),
        ),
    ]
