# Generated by Django 6.0.5 on 2026-06-06 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('influencers', '0002_alter_influencerprofile_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkedCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='campaigns.campaign')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_campaigns', to='influencers.influencerprofile')),
            ],
            options={
                'unique_together': {('influencer', 'campaign')},
            },
        ),
    ]
