# Generated by Django 6.0.5 on 2026-05-30 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niche', models.CharField(choices=[('fashion', 'Fashion'), ('beauty', 'Beauty'), ('fitness', 'Fitness'), ('food', 'Food & Cooking'), ('travel', 'Travel'), ('tech', 'Tech'), ('gaming', 'Gaming'), ('lifestyle', 'Lifestyle'), ('business', 'Business'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('health', 'Health & Wellness'), ('parenting', 'Parenting'), ('finance', 'Finance'), ('other', 'Other')], default='lifestyle', max_length=50)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('collab_price_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('collab_price_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('languages', models.CharField(blank=True, default='English', max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='influencer_covers/')),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_collaborations', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('link', 'Link')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('link_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='influencers.influencerprofile')),
            ],
        ),
    ]
